### ISSUE TITLE
Make mount url configurable

### ISSUE THREAD

**Issue by n-rodriguez** [lbeder/health-monitor-rails#45]
Hi there!

It would be nice to make the mount url configurable :

```ruby
mount HealthMonitor::Engine, at: '/check'
```

instead of 

```ruby
mount HealthMonitor::Engine, at: '/'
```

**Comment by n-rodriguez** [comment]
> Hi,
> This is a breaking change, so the this feature should be backward compatible and tested accordingly. At the moment, it seems that some of these tests are missing and thathttps://github.com/[/pull/46](https://github.com/lbeder/health-monitor-rails/pull/46) doesn't pass the CI tests in full.

did you read the Travis report?

**Comment by lbeder** [comment]
Regardless, CI needs to be green. Always. If it's only due to a new behavior of Rubocop - it needs to be taken care before this PR can be fixed and I'll do it later. Please keep in mind that you are still missing tests against multiple configurations. 

re: version bump - this needs to be coordinated and shouldn't be taken lightly.

**Comment by n-rodriguez** [comment]
> Please keep in mind that you are still missing tests against multiple configurations.

what are you talking about? I didn't know you could mount health url multiple times.
can you show me where it is?

**Comment by lbeder** [comment]
The needs to be against multiple/configurable dummy apps. I'm not familiar with a different method.
